카카오 로그인
KEP-STUDY/review-campus pull request #8
Opened 2021-05-09 16:06 UTC by BuildTheTruth

- axios customizing : 핸들러 콜백을 프로퍼티로 받아서 try-catch문 중복 제거
```ts
const customAxios = axios.create({
  baseURL: `/api`,
  headers: {
    'Content-Type': 'application/json',
    'Accept': 'application/json;charset=utf-8',
  },
})

const request = async <T>({
  method = 'get',
  url,
  data,
  config,
  onSuccess,
  onError,
}: RequestProps<T>) => {
  try {
    const res = await customAxios[method]<T>(url, data, config)
    await onSuccess(res)
  } catch (err) {
    await onError(err)
  }
}

```
- API 호출 및 핸들링 로직 page 컴포넌트로 이동
- API 추상화 : `getToken()`, `getProfile()` ( api/auth )
- [서버] token 값을 통해 profile 정보 받아오는 `getProfile()` 추가 (디렉토리 구조 확정되면 변경할 예정)

2021-05-12 11:43 UTC, beingPracticer reviewed
ㄷㄷ

2021-05-12 11:49 UTC, beingPracticer requested changes
👍

2021-05-12 11:49 UTC, beingPracticer commented on apps/client/api/auth.ts
> +    grant_type: 'authorization_code',
env로 빼는게 어떤가요?

2021-05-12 11:49 UTC, beingPracticer commented on apps/client/pages/index.tsx
> +    alert('프로필 로드 실패')
alert 빼주세요

2021-05-13 08:17 UTC, BuildTheTruth commented on apps/client/pages/index.tsx
> +    alert('프로필 로드 실패')
왜죠?

2021-05-13 08:18 UTC, BuildTheTruth commented on apps/client/api/auth.ts
> +    grant_type: 'authorization_code',
음 env파일에는 보안상 문제있는 부분만 가져가면 좋을 것 같아요.

2021-05-15 06:39 UTC, beingPracticer commented on apps/client/pages/index.tsx
> +    alert('프로필 로드 실패')
alert로 표시하다보면 나중에 실수로 배포시에 포함되어질수도 있고 디버깅에 바로 노출되어서 편리하지만, 과도하게 사용될 경우 분별이 안되어서 복잡해질 수 있다고 생각해요

2021-05-15 11:18 UTC, BuildTheTruth commented on apps/client/pages/index.tsx
> +    alert('프로필 로드 실패')
추후에는 직접 만든 Alert 컴포넌트로 표시할 예정입니다. 사용자입장에서 아무 인터랙션 없이 로그인이 되지 않는 것이 더 문제가 될 것이라고 판단하여 넣은 것입니다.

2021-05-15 11:48 UTC, beingPracticer approved these changes

2021-05-16 09:31 UTC, merged